### ISSUE TITLE
One press preview in browser

### ISSUE THREAD

**Issue by Kristinita** [alexnj/SublimeOnSaveBuild#38]
I using Slim language, Live Reload and SublimeOnSaveBuild. 

I have to press <kbd>Ctrl+S</kbd> 2 times then, to view the result in my browser.

![2 time LiveReload](http://i.imgur.com/s70FS8a.gif)

Stack trace, if needs:

```
    key evt: control+s
    command: save
    {"command": "reload", "apply_images_live": null, "apply_css_live": null, "path": "SashaSlim.slim", "apply_js_live": null}
    INFO:WebSocketClient:Remove from clients table <LiveReload.server.WebSocketClient.WebSocketClient object at 0x045E5370>
    ERROR:WebSocketClient:WebSocket error
    Traceback (most recent call last):
      File "E:\Sublime Text 3\Data\Packages\LiveReload\server\WebSocketClient.py", line 84, in __init__
        data = self.socket.recv(1024)
    OSError: [WinError 10038] Сделана попытка выполнить операцию на объекте, не являющемся сокетом
    INFO:WebSocketClient:Remove from clients table <LiveReload.server.WebSocketClient.WebSocketClient object at 0x045E5370>
    INFO:WebSocketClient:new client ('127.0.0.1', 54505)
    INFO:WebSocketClient:new client ('127.0.0.1', 54506)
    INFO:WebSocketClient:new client ('127.0.0.1', 54507)
    INFO:WebSocketClient:Add to clients table <LiveReload.server.WebSocketClient.WebSocketClient object at 0x04BB8D90>
    INFO:WebSocketClient:{'payload': b'{"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"2.0.8","ext":"Firefox","extver":"2.1.1"}', 'close_code': None, 'close_reason': None, 'fin': 1, 'hlen': 4, 'mask': b'Ni\xe4X', 'length': 170, 'opcode': 1, 'left': 0}
    INFO:WebSocketClient:Command: hello
    INFO:WebSocketClient:{'payload': b'{"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"file:///E:/%D0%9A%D0%B8%D1%80%D0%BE%D0%BB%D0%B0%D0%B9%D0%BD%D0%B0/SashaSlim.html"}', 'close_code': None, 'close_reason': None, 'fin': 1, 'hlen': 4, 'mask': b'\xac\x9d\x06{', 'length': 160, 'opcode': 1, 'left': 0}
    INFO:WebSocketClient:Command: info
    b'{"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"file:///E:/%D0%9A%D0%B8%D1%80%D0%BE%D0%BB%D0%B0%D0%B9%D0%BD%D0%B0/SashaSlim.html"}'
    key evt: control+s
    command: save
    {"command": "reload", "apply_images_live": null, "apply_css_live": null, "path": "SashaSlim.slim", "apply_js_live": null}
    INFO:WebSocketClient:Remove from clients table <LiveReload.server.WebSocketClient.WebSocketClient object at 0x04BB8D90>
    ERROR:WebSocketClient:WebSocket error
    Traceback (most recent call last):
      File "E:\Sublime Text 3\Data\Packages\LiveReload\server\WebSocketClient.py", line 84, in __init__
        data = self.socket.recv(1024)
    OSError: [WinError 10038] Сделана попытка выполнить операцию на объекте, не являющемся сокетом
    INFO:WebSocketClient:Remove from clients table <LiveReload.server.WebSocketClient.WebSocketClient object at 0x04BB8D90>
    INFO:WebSocketClient:new client ('127.0.0.1', 54508)
    INFO:WebSocketClient:new client ('127.0.0.1', 54509)
    INFO:WebSocketClient:new client ('127.0.0.1', 54510)
    INFO:WebSocketClient:Add to clients table <LiveReload.server.WebSocketClient.WebSocketClient object at 0x04B60E30>
    INFO:WebSocketClient:{'payload': b'{"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"2.0.8","ext":"Firefox","extver":"2.1.1"}', 'close_code': None, 'close_reason': None, 'fin': 1, 'hlen': 4, 'mask': b'4\x86\x94\x0c', 'length': 170, 'opcode': 1, 'left': 0}
    INFO:WebSocketClient:Command: hello
    INFO:WebSocketClient:{'payload': b'{"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"file:///E:/%D0%9A%D0%B8%D1%80%D0%BE%D0%BB%D0%B0%D0%B9%D0%BD%D0%B0/SashaSlim.html"}', 'close_code': None, 'close_reason': None, 'fin': 1, 'hlen': 4, 'mask': b'E\xc5N\x87', 'length': 160, 'opcode': 1, 'left': 0}
    INFO:WebSocketClient:Command: info
    b'{"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"file:///E:/%D0%9A%D0%B8%D1%80%D0%BE%D0%BB%D0%B0%D0%B9%D0%BD%D0%B0/SashaSlim.html"}'
```

If needs the necessary information, as I have set LiveReload, I give it.

_Question_: Can I do so that I can see a preview in the browser after one press <kbd>Ctrl+S</kbd>, not two? Maybe other instruments, not necessarily LiveReload.

Thanks for great plugin.

**Comment by Kristinita** [comment]
I solved my ploblem with usage [Improved Macros](https://github.com/skuroda/ImprovedMacros) plugin. I add in my `Key Bindings - User` file these settings:

```
// Double save
    {
        "keys": ["alt+context_menu"], "command": "run_multiple_commands",
        "args": {
            "commands": [{
                "command": "save",
            },{
                "command": "save",
                "delay": 700
            },
        ]
        }
     },
```
